version: '3'
services:
  mfsmaster:
    build: ./moosefs-master
    container_name: "mfsmaster"
    networks:
      moosefsnet:
        ipv4_address: "172.23.0.2"
    volumes:
            - ./data/master/meta:/var/lib/mfs
    hostname: mfsmaster
    environment:
      - MFS_ENV=TEST 
      # In the TEST environment, if metadata.mfs file or other metadata files
      # like metdata.mfs.back and changelog.0.mfs are missing, the script will
      # create an EMPTY metadata file!
      # When MFS_ENV=PROD metdata.mfs file will not be created!

  mfscgi:
    build: ./moosefs-cgi
    container_name: "mfscgi"
    networks:
      moosefsnet:
        ipv4_address: "172.23.0.3"
    ports:
      - "9425:9425"
    depends_on:
      - mfsmaster

  mfsmetalogger:
    build: ./moosefs-metalogger
    container_name: "mfsmetalogger"
    networks:
      moosefsnet:
        ipv4_address: "172.23.0.4"
    volumes:
      - ./data/metalogger/meta:/var/lib/mfs
    environment:
      - MFS_ENV=TEST
      # In the TEST environment, if metadata.mfs file or other metadata files
      # like metdata.mfs.back and changelog.0.mfs are missing, the script will
      # create an EMPTY metadata file!
      # When MFS_ENV=PROD metdata.mfs file will not be created!
    depends_on:
      - mfsmaster

  mfschunkserver1:
    build: ./moosefs-chunkserver
    container_name: "mfschunkserver1"
    environment:
      - LABELS=M
      #- SIZE=100
    links:
      - mfsmaster
    # env_file:
    #   - ./env.list
    networks:
      moosefsnet:
        ipv4_address: "172.23.0.11"
    volumes:
            - ./data/cs1/hdd0:/mnt/hdd0
            - ./data/cs1/meta:/var/lib/mfs
    depends_on:
      - mfsmaster
  mfschunkserver2:
    build: ./moosefs-chunkserver
    container_name: "mfschunkserver2"
    environment:
      - LABELS=M,B
      #- SIZE=100
    links:
      - mfsmaster
    # env_file:
    #   - ./env.list
    networks:
      moosefsnet:
        ipv4_address: "172.23.0.12"
    volumes:
            - ./data/cs2/hdd0:/mnt/hdd0
            - ./data/cs2/meta:/var/lib/mfs
    depends_on:
      - mfsmaster
  weba:
    build: ./weba
    container_name: weba
    volumes:
            - ./data/cs1/hdd0:/mnt/hdd0
            - ./data/cs1/meta:/var/lib/mfs
    ports:
      - "6002:6000"
    links:
      - mfsmaster
    networks:
      moosefsnet:
        ipv4_address: "172.23.0.13"
    depends_on:
      - mfschunkserver1
      # - chunkserver2
    # restart: always

  webb:
    build: ./webb
    container_name: webb
    volumes:
            - ./data/cs2/hdd0:/mnt/hdd0
            - ./data/cs2/meta:/var/lib/mfs
    ports:
      - "6001:6000"
    links:
      - mfsmaster
    networks:
      moosefsnet:
        ipv4_address: "172.23.0.14"
    depends_on:
      # - chunkserver1
      - mfschunkserver2
  mfsclient:
    build: ./moosefs-client
    container_name: "mfsclient"
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
    stdin_open: true
    tty: true
    links:
      - mfsmaster
    networks:
      moosefsnet:
        ipv4_address: "172.23.0.100"
    depends_on:
      - mfsmaster
      - mfschunkserver1
      - mfschunkserver2
      # - mfschunkserver3
      # - mfschunkserver4

networks:
  moosefsnet:
    driver: bridge
    ipam:
     config:
       - subnet: 172.23.0.0/16
